# Generated by Django 3.0.6 on 2020-06-18 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20200618_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 11, 41, 33, 888715)),
        ),
    ]
