# Generated by Django 3.0.6 on 2020-06-18 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20200618_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 14, 4, 51, 906825)),
        ),
    ]
